FrontEnd/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DHCDFrontEnd.Controllers
{
    public class ExperienceController : Controller
    {
        public ActionResult Notifications()
        {
            return View();
        }

        public ActionResult SysNavigation()
        {
            return View();
        }
    }
}

FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="description" content="mobile first, app, web app, responsive, admin dashboard, flat, flat ui">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/font.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/plugin.css">
    <!--[if lt IE 9]>
      <script src="/js/ie/respond.min.js"></script>
      <script src="/js/ie/html5.js"></script>
      <script src="/js/ie/excanvas.js"></script>
    <![endif]-->
    <script src="/js/jquery.min.js"></script>
</head>
<body>
    <!-- header -->
    <header id="header" class="navbar">
        @if (HttpContext.Current.User.Identity.IsAuthenticated)
        {
            <ul class="nav navbar-nav navbar-avatar pull-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="hidden-xs-only">@(Session["LocationAddress"]?.ToString())</span> |
                        <span class="hidden-xs-only">@HttpContext.Current.User.Identity.Name</span>
                        <span class="thumb-small avatar inline"><img src="/images/avatar.png" class="img-circle"></span>
                        <b class="caret hidden-xs-only"></b>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="#">Settings</a></li>
                        <li><a href="/profile">Profile</a></li>
                        <li><a href="#"><span class="badge bg-danger pull-right">3</span>Notifications</a></li>
                        <li class="divider"></li>
                        <li><a href="docs.html">Help</a></li>
                        <li><a href="/logout">Logout</a></li>
                    </ul>
                </li>
            </ul>
        }

        <a class="navbar-brand" href="#">DHCD</a>
        <button type="button" class="btn btn-link pull-left nav-toggle visible-xs" data-toggle="class:slide-nav slide-nav-left" data-target="body">
            <i class="fa fa-bars fa-lg text-default"></i>
        </button>
        <ul class="nav navbar-nav hidden-xs">
            <li>
                <!--Notification-->
                @{Html.RenderAction("Notifications", "Experience");}
                <!--Notification-->
            </li>
            <li><div class="m-t-small"><a class="btn btn-sm btn-info" data-toggle="modal" href="#modal"><i class="fa fa-fw fa-plus"></i> POST</a></div></li>
            <li class="dropdown shift" data-toggle="shift:appendTo" data-target=".nav-primary .nav">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cog fa-lg visible-xs visible-xs-inline"></i>Settings <b class="caret hidden-sm-only"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#" data-toggle="class:navbar-fixed" data-target='body'>
                            Navbar
                            <span class="text-active">auto</span>
                            <span class="text">fixed</span>
                        </a>
                    </li>
                    <li class="hidden-xs">
                        <a href="#" data-toggle="class:nav-vertical" data-target="#nav">
                            Nav
                            <span class="text-active">vertical</span>
                            <span class="text">horizontal</span>
                        </a>
                    </li>
                    <li class="divider hidden-xs"></li>
                    <li class="dropdown-header">Colors</li>
                    <li>
                        <a href="#" data-toggle="class:bg bg-black" data-target='.navbar'>
                            Navbar
                            <span class="text-active">white</span>
                            <span class="text">inverse</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" data-toggle="class:bg-light" data-target='#nav'>
                            Nav
                            <span class="text-active">inverse</span>
                            <span class="text">light</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <form class="navbar-form pull-left shift" action="" data-toggle="shift:appendTo" data-target=".nav-primary">
            <i class="fa fa-search text-muted"></i>
            <input type="text" class="input-sm form-control" placeholder="Search">
        </form>
    </header>
    <!-- / header -->
    <!-- nav -->
    @{Html.RenderAction("SysNavigation", "Experience");}
    <!-- / nav -->
    <!--body-->
    @RenderBody()
    <!--body-->
    <!--Model-->
    <div class="modal inmodal" id="modal_loading" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center" style="background: rgba(255, 255, 255, 0)">
                    <img src="~/images/sending-1.gif" />
                </div>
            </div>
        </div>
    </div>
    <!--Model-->

    <footer id="footer">
        <div class="text-center padder clearfix">
            <p>
                <small>&copy; Vingroup JSC 2019</small><br><br>
            </p>
        </div>
    </footer>
    <a href="#" class="hide slide-nav-block" data-toggle="class:slide-nav slide-nav-left" data-target="body"></a>
    <!-- / footer -->
    <!-- Bootstrap -->
    <script src="/js/bootstrap.js"></script>
    <!-- app -->
    <script src="/js/app.js"></script>
    <script src="/js/app.plugin.js"></script>
    <script src="/js/app.data.js"></script>

    <!-- Sparkline Chart -->
    <script src="/js/charts/sparkline/jquery.sparkline.min.js"></script>
    <!-- Easy Pie Chart -->
    <script src="/js/charts/easypiechart/jquery.easy-pie-chart.js"></script>

    <!-- fuelux -->
    <script src="/js/fuelux/fuelux.js"></script>
    <!-- datepicker -->
    <script src="/js/datepicker/bootstrap-datepicker.js"></script>
    <!-- file input -->
    <script src="/js/file-input/bootstrap.file-input.js"></script>
    <!-- combodate -->
    <script src="/js/combodate/moment.min.js"></script>
    <script src="/js/combodate/combodate.js"></script>
    <!-- select2 -->
    <script src="/js/select2/select2.min.js"></script>
    <!--Notify-->
    <link href="/js/growl/jquery.growl.css" rel="stylesheet" />
    <script src="/js/growl/jquery.growl.js"></script>
    <!--Cookie-->
    <script src="/js/cookie/jquery.cookie.js"></script>
    <!--validate-->
    <script src="/js/validate/jquery.validate.min.js"></script>
    <script src="/js/moment.js"></script>
</body>
</html>

FrontEnd/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/font.css">
    <link rel="stylesheet" href="/css/style.css">
    <!--[if lt IE 9]>
      <script src="/js/ie/respond.min.js"></script>
      <script src="/js/ie/html5.js"></script>
    <![endif]-->

    <script src="/js/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/js/bootstrap.js"></script>
</head>
<body>
    <!-- header -->
    <header id="header" class="navbar bg bg-black">
        <a class="navbar-brand" href="/" style="padding:0px;">DHCD</a>
    </header>
    <!-- / header -->
    <section id="content">
        <div class="main padder">
            @RenderBody()
        </div>
    </section>
    <!-- footer -->
    <footer id="footer">
        <div class="text-center padder clearfix">
            <p>
                <small>&copy; Vingroup JSC 2019</small><br><br>
                <a href="#" class="btn btn-xs btn-circle btn-twitter"><i class="fa fa-twitter"></i></a>
                <a href="#" class="btn btn-xs btn-circle btn-facebook"><i class="fa fa-facebook"></i></a>
                <a href="#" class="btn btn-xs btn-circle btn-gplus"><i class="fa fa-google-plus"></i></a>
            </p>
        </div>
    </footer>

    <!-- / footer -->
    <!-- app -->
    <script src="/js/app.js"></script>
    <script src="/js/app.plugin.js"></script>
    <!--Cookie-->
    <script src="/js/cookie/jquery.cookie.js"></script>
    <!--validate-->
    <script src="/js/validate/jquery.validate.min.js"></script>
</body>
</html>

FrontEnd/Views/Shared/_LayoutReport.cshtml
@RenderBody()

FrontEnd/Views/Shared/_LayoutTemplate.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body style="margin:0px;">
    @RenderBody()
</body>
</html>