FrontEnd/Controllers/EventConfigController.cs
using DataService;
using DataService.ActionServices;
using DataService.DomainModel;
using DHCDFrontEnd.Extensions;
using Excel;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VG.Common;

namespace DHCDFrontEnd.Controllers
{
    [Authorize]
    public class EventConfigController : ControllerExtension
    {
        private IAuthenticationService authenticationService;
        public EventConfigController()
        {
            authenticationService = new AuthenticationService(new HttpContextWrapper(System.Web.HttpContext.Current));
        }

        public ActionResult EConfig(string eID, string searchString, int? page)
        {
            if (!string.IsNullOrEmpty(eID))
            {
                int _eventID = 0;
                if (CommonHelper.HashDecodeId(eID, out _eventID))
                {
                    EventDetail ModelConfig = new EventDetail();

                    ModelConfig.SeletedEvent = DataAccess.GetEventByID(_eventID);
                    ModelConfig.SeletedPL = DataAccess.GetPLByID(ModelConfig.SeletedEvent.PL_ID);
                    ModelConfig.ListStockholder = DataAccess.GetStockholderInvite(_eventID, searchString, page);

                    ViewBag.Showing = "showing "+ ModelConfig.ListStockholder.FirstItemOnPage + "-"+ ModelConfig.ListStockholder.LastItemOnPage + " of "+ ModelConfig.ListStockholder.TotalItemCount + " items";



                    int totalNullBarcode = DataAccess.GetNumNotYetGenBarcode(_eventID);
                    if(totalNullBarcode > 0)
                    {
                        int TotalInvi = DataAccess.CountStockholderInvite(_eventID);
                        ViewBag.BarcodeInfo = "<div class=\"alert alert-warning alert-block\" style=\"margin-bottom:0px;padding:7px;\"><i class=\"fa fa-bell - o\"></i>Warning! Có " + totalNullBarcode + " barcode/"+ TotalInvi + " cổ đông chưa được tạo</div>";
                    }
                    else
                    {
                        ViewBag.BarcodeInfo = "<div class=\"alert alert-success\" style=\"margin-bottom:0px;padding:7px;\"><i class=\"fa fa-check fa-lg\"></i><strong>Well done!</strong> Tất cả Barcode đã được tạo.</div>";
                    }

                    
                    ViewBag.CurrentSearch = searchString;

                    return View(ModelConfig);
                }
                else
                {
                    return Redirect("/NotFound");
                }
            }
            else
            {
                return Redirect("/NotFound");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CompressFilter(Order = 1)]
        public JsonResult UploadExcel()
        {
            var files = Request.Files;
            try
            {
                var uploadFile = files[0];
                if (uploadFile.FileName.IndexOfAny(Path.GetInvalidFileNameChars()) != -1)
                {
                    return Json(new { status = 0, mes = "File không được chấp nhận" });
                }
                if (string.IsNullOrEmpty(uploadFile.FileName)) { return Json(new { status = 0, mes = "File không được chấp nhận" }); };
                string ext = Path.GetExtension(uploadFile.FileName).Replace(".", "").ToLower();
                if (!((ext == "xlsx") || (ext == "xls") || (ext == "csv"))) { return Json(new { status = 0, mes = "File không được chấp nhận" }); };

                string stEventID = files.GetKey(0);

                string dFolder = stEventID + "/";
                string targetLocation = ConstKey.LocalDir + dFolder;
                if (!Directory.Exists(targetLocation)) Directory.CreateDirectory(targetLocation);

                var path = Path.Combine(targetLocation, CommonHelper.CreateFileName() + "_" + uploadFile.FileName);
                uploadFile.SaveAs(path);

                FileStream streamOpen = System.IO.File.Open(path, FileMode.Open, FileAccess.Read);
                IExcelDataReader excelReader = null;
                switch (ext)
                {
                    case "xls":
                        //Excel 97-03
                        excelReader = ExcelReaderFactory.CreateBinaryReader(streamOpen);
                        break;
                    case "xlsx":
                        //Excel 07
                        excelReader = ExcelReaderFactory.CreateOpenXmlReader(streamOpen);
                        break;
                }

                excelReader.IsFirstRowAsColumnNames = true;
                DataSet result = excelReader.AsDataSet();
                DataTable dtResult = result.Tables[0];

                //STEP 1: IMPORT
                //1.-Save DataTable to some where . I'm temp save to Session :(
                DataImport dataImport = new DataImport()
                {
                   dtResult = dtResult,
                   originalFileName = uploadFile.FileName,
                   excelPath = path
                };
                Session["dtStockhodler"] = dataImport;

                List<string> columnNames = dtResult.Columns.Cast<DataColumn>().Select(x => x.ColumnName).ToList();

                #region Chỉ là tạo Example data để người dùng dễ hình dung khi mapping
                int _loop = (dtResult.Rows.Count > 5) ? 5 : dtResult.Rows.Count;
                string[][] myTable = new string[_loop][];
                for(int i = 0; i < _loop; i++)
                {
                    int columnCount = 0;
                    string[] myTableRow = new string[columnNames.Count];
                    foreach (string cname in columnNames)
                    {
                        myTableRow[columnCount] = dtResult.Rows[i][cname].ToString();
                        columnCount++;
                    }
                    myTable[i] = myTableRow;
                }
                var table2DArray = myTable.ToArray();
                #endregion


                return Json(new { data = columnNames, example = table2DArray, status = 1 });
            }
            catch(Exception ex)
            {
                return Json(new { status = 0, mes = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CompressFilter(Order = 1)]
        public JsonResult SaveImportSchema()
        {
            try
            {
                int _eID = 0;
                if (string.IsNullOrEmpty(Request.Form["eID"]))
                {
                    return Json(new { status = 0, mes = "Không có ID sự kiện" });
                }
                else if (!CommonHelper.HashDecodeId(Request.Form["eID"], out _eID))
                {
                    return Json(new { status = 0, mes = "Không có ID sự kiện" });
                }

                DataImport dataImport = (DataImport) Session["dtStockhodler"];

                tblSharreholdImportBatch objBatch = new tblSharreholdImportBatch();
                objBatch.Created_Acc = authenticationService.GetAuthenticatedUser().Acc_ID;
                objBatch.Created_Date = DateTime.Now;
                objBatch.Batch_Status = 0;
                objBatch.Event_ID = _eID;
                objBatch.TotalRow = dataImport.dtResult.Rows.Count;
                objBatch.OriFileName = dataImport.originalFileName;
                objBatch.DirExcel = dataImport.excelPath;
                objBatch.NumInsert = 0;
                objBatch.NumError = 0;
                objBatch.CountNumStock = 0;


                DataAccess.InsertBatchImport(objBatch);
                int _batchID = objBatch.Batch_ID;

                List<tblStockholderInvite> listStockholder = new List<tblStockholderInvite>();
                List<ImportLog> importlong = new List<ImportLog>();

                DateTime CreatedDate = DateTime.Now;
                int accID = authenticationService.GetAuthenticatedUser().Acc_ID;

                int countError = 0;
                int rowIndex = 0;
                long TotalNumStock = 0;
                if (dataImport.dtResult != null && dataImport.dtResult.Rows.Count > 0)
                {
                    foreach (DataRow row in dataImport.dtResult.Rows)
                    {
                        rowIndex++;
                        tblStockholderInvite tempUser = new tblStockholderInvite();

                        #region nhoms NotNull return if null
                        if (Request.Form["opName"] != "---select---")
                        {
                            tempUser.FullName = string.IsNullOrEmpty(row[Request.Form["opName"]].ToString()) ? " " : row[Request.Form["opName"]].ToString();
                        }
                        else
                        {
                            return Json(new { status = -1, mes = "Mapping thiếu dữ liệu chỉ định cho cột không được phép NULL" });
                        }

                        if (Request.Form["opAddress"] != "---select---")
                        {
                            tempUser.Address = string.IsNullOrEmpty(row[Request.Form["opAddress"]].ToString()) ? " " : row[Request.Form["opAddress"]].ToString();
                        }
                        else
                        {
                            return Json(new { status = -1, mes = "Mapping thiếu dữ liệu chỉ định cho cột không được phép NULL" });
                        }

                        if (Request.Form["opQuantity"] != "---select---")
                        {
                            long QuantityValue = 0;
                            if (long.TryParse(row[Request.Form["opQuantity"]].ToString(), out QuantityValue))
                            {
                                tempUser.Quantity = QuantityValue;
                            }
                            else
                            {
                                tempUser.Quantity = 0;
                                countError++;

FrontEnd/Views/EventConfig/EConfig.cshtml
@using VG.Common;
@using PagedList.Mvc;
@using PagedList;
@using DataService;
@{
    /**/
    ViewBag.Title = "Danh sách cổ đông";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="content">
    <section class="main padder">
        <div class="clearfix">
            <h3><i class="fa fa-magic"></i> @Model.SeletedPL.PL_DisplayName - @Model.SeletedEvent.Event_Name</h3>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <!-- .breadcrumb -->
                <ul class="breadcrumb">
                    <li><a href="/mastereventlist?p=@CommonHelper.HashEncodeId(Model.SeletedPL.PL_ID)"><i class="fa fa-home"></i>Danh sách đại hội</a></li>
                    <li><a href="/EventDasboard/Dashboard?e=@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)">@Model.SeletedPL.PL_DisplayName - @Model.SeletedEvent.Event_Name</a></li>
                    <li class="active">Danh sách cổ đông</li>
                </ul>
                <!-- / .breadcrumb -->
            </div>
            <div class="col-lg-12">
                <section class="toolbar clearfix m-b">
                    <a href="#" class="btn btn-circle"><i class="fa fa-plus"></i>More</a>
                    <a href="/Validation/barcode?eID=@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)" class="btn btn-success btn-circle"><i class="fa fa-check"></i>Kiểm tra giấy mời</a>
                </section>

                <section class="panel">
                    <div class="row">
                        <div class="col-lg-12">
                            <!--Table danh sach khach moi-->
                            <section class="panel">
                                <header class="panel-heading">
                                    Danh sách cổ đông
                                </header>
                                <div class="panel-body">
                                    <div class="row text-small">
                                        <div class="col-sm-4">
                                            <div class="btn-group">
                                                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                                                <ul class="dropdown-menu">
                                                    @*<li><a href="#">Xuất in vé mời</a></li>
                                                    <li class="divider"></li>*@
                                                    <li><a href="javascript:genallbarcode('@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)');">Tạo barcode</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            @Html.Raw(ViewBag.BarcodeInfo)
                                        </div>
                                        <div class="col-sm-4">
                                            @using (Html.BeginForm("EConfig", "EventConfig", FormMethod.Get))
                                            {
                                                <div class="input-group">
                                                    <input type="hidden" name="eID" value="@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)" />
                                                    <input type="text" class="input-sm form-control" name="SearchString" placeholder="Search" value="@ViewBag.CurrentSearch">
                                                    <span class="input-group-btn">
                                                        <button class="btn btn-sm btn-white" type="submit">Go!</button>
                                                    </span>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped b-t text-small">
                                        <thead>
                                            <tr>
                                                <th>Mã số CD</th>
                                                <th>Barcode</th>
                                                <th>Họ và tên</th>
                                                <th>Địa chỉ</th>
                                                <th>Số CMND/HC</th>
                                                <th>Ngày cấp</th>
                                                <th>Số lượng</th>
                                                <th width="30">

                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model.ListStockholder)
                                            {
                                            <tr>
                                                <td>@CommonHelper.HashEncodeId(item.SHID)</td>
                                                <td><img src="data:image/png;base64,@item.BarCode" height="22" onerror="this.style.display='none'" /></td>
                                                <td>@item.FullName</td>
                                                <td>@item.Address</td>
                                                <td>@item.CardID</td>
                                                @if (item.CardDate != null)
                                                {
                                                    <td>@String.Format("{0:dd/mm/yyyy}", item.CardDate)</td>
                                                }
                                                else
                                                {
                                                    <td></td>
                                                }
                                                <td>@item.Quantity</td>
                                                <td>
                                                    <div class="btn-group">
                                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-text-o"></i></a>
                                                        <ul class="dropdown-menu pull-right">
                                                            <li><a href="javascript:modelpreview('@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)','@CommonHelper.HashEncodeId(item.SHID)');">Xem thư mời</a></li>
                                                            @*<li><a href="javascript:printinvitation('@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)','@CommonHelper.HashEncodeId(item.SHID)');">In thư mời</a></li>*@
                                                            @if (item.sType == 1)
                                                            {
                                                                <li><a href="/Template/Invitation?eID=@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)&uID=@CommonHelper.HashEncodeId(item.SHID)" target="_blank" media="print">In thư mời</a></li>
                                                            }
                                                            else
                                                            {
                                                                <li><a href="/Template/InvitationEng?eID=@CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID)&uID=@CommonHelper.HashEncodeId(item.SHID)" target="_blank" media="print">In thư mời</a></li>
                                                            }
                                                            <li><a href="#">Sửa thông tin</a></li>
                                                            <li class="divider"></li>
                                                            <li><a href="#">Xóa khỏi danh sách</a></li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>
                                <footer class="panel-footer">
                                    <div class="row">
                                        <div class="col-sm-4 hidden-xs">
                                        </div>
                                        <div class="col-sm-3 text-center">
                                            <small class="text-muted inline m-t-small m-b-small">@ViewBag.Showing</small>
                                        </div>
                                        <div class="col-sm-5 text-right text-center-sm">
                                            Page @(Model.ListStockholder.PageCount < Model.ListStockholder.PageNumber ? 0 : Model.ListStockholder.PageNumber) of @Model.ListStockholder.PageCount
                                            @{
                                                string eID = CommonHelper.HashEncodeId(Model.SeletedEvent.Event_ID);
                                            }
                                            @Html.PagedListPager((IPagedList) Model.ListStockholder, page => Url.Action("EConfig", new { eID, currentFilter = ViewBag.CurrentSearch, page }))
                                        </div>
                                    </div>
                                </footer>
                            </section>
                            <!--Table danh sach khach moi-->
                        </div>
                    </div>
                </section>
            </div>

        </div>

    </section>
</section>


<div class="modal fade" id="myModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:1000px;">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Xem thư mời</h4>
            </div>
            <div class="modal-body" id="pfdViewer">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        $.validator.messages.required = "Thông tin bắt buộc";

        $.validator.addMethod("regx", function (value, element, regexpr) {
            return regexpr.test(value);
        }, 'Không chấp nhận ký tự đặc biệt');
    });



    function modelpreview(eid, uid) {
        $('#pfdViewer').load('/Template/Invitation?eID=' + eid + '&uID=' + uid, function () {
            $('#myModal').modal({ show: true });
        });
    }

    function printinvitation(eid, uid) {
        var sendInfo = {
            eID: eid,
            uID: uid
        };
        $.ajax({
            type: "POST",
            url: "/EventBus/EventMessPrinting",
            dataType: "json",
            success: function (result) {
                console.log(result);
                $.growl.notice({ message: "Printing...!" });
            },
            data: sendInfo
        });
    }

    function genallbarcode(eid)
    {
        var sendInfo = {
            eID: eid
        };

        $.ajax({
            type: "POST",
            url: "/EventBus/GenAllBarcode",
            dataType: "json",
            success: function (result) {
                console.log(result);
                $.growl.notice({ message: "Tác vụ đang được thực hiện!" });
            },
            data: sendInfo
        });
    }
</script>